from langchain_groq import ChatGroq
from langchain_community.tools.tavily_search import TavilySearchResults
from langgraph.prebuilt import create_react_agent
from langchain_core.messages import AIMessage, HumanMessage

from app.config.settings import settings 


def get_response_from_ai_agents(llm_id: str, query: list[str] | str, allow_search: bool, system_prompt: str) -> str:

    llm = ChatGroq(model=llm_id, api_key=settings.GROQ_API_KEY)
    tools = [TavilySearchResults(max_results=2, api_key=settings.TAVILY_API_KEY)] if allow_search else []
    
    agent = create_react_agent(
        model=llm,
        tools=tools,
        prompt=system_prompt,
    )

    # Convert raw strings into HumanMessage objects for LangGraph compatibility
    if isinstance(query, list):
        formatted_messages = [HumanMessage(content=msg) if isinstance(msg, str) else msg for msg in query]
    else:
        formatted_messages = [HumanMessage(content=str(query))]

    state = {
        "messages": formatted_messages
    }
    
    response = agent.invoke(state)
    messages = response.get("messages", [])
    ai_messages = [message.content for message in messages if isinstance(message, AIMessage)]
    
    if not ai_messages:
        return "No response generated by the AI agent."
        
    return ai_messages[-1]
